config/routes.rb
MoneyCollector::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions
  resources :users

  resources :countries, :except => :destroy do
    collection do
      get :visited
    end

    member do
      post :buy_currency
    end
  end
  resources :currencies, :only => [:index, :show]
  
  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessor :buy_all
  
  validate :code, :presence => true

  has_many :country_currencies, :dependent => :destroy

  scope :visited, where("visited_count > 0")

  before_save :process_buy_all

  def visited?
    visited_count > 0
  end
  
  private

  def process_buy_all
    if buy_all == 'true'
      Service.data.each do |d|
        if d[:country_code] == code
          country_currencies.create!(:currency_code => d[:currency_code], :visited_at => Time.now) unless
            country_currencies.exists?(:currency_code => d[:currency_code])
        end
      end
    else
      country_currencies.destroy_all
    end
  end
end

app/models/country_currency.rb
class CountryCurrency < ActiveRecord::Base
  belongs_to :country, :counter_cache => 'visited_count'

  validate :country_id, :currency_code, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery

  protected

  def get_data
    @data = Service.data
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_filter :login_required, :except => [:show, :visited]
  before_filter :find_country,   :only => [:show, :update, :buy_currency]
  before_filter :get_data,       :only => [:index, :show]

  def index
    @countries = Country.all
  end

  def visited
    @countries = Country.visited
  end
  
  def show
    @country_currency = CountryCurrency.new
  end

  def buy_currency
    @country.country_currencies.create!(params[:country_currency]) unless @country.country_currencies.exists?(:currency_code => params[:country_currency][:currency_code])
    flash[:notice] = 'Saved'
    redirect_to country_path(@country.code)
  end

  def update
    @country.update_attributes(params[:country])
    flash[:notice] = 'Saved'
    
    redirect_to country_path(@country.code)
  end

  private

  def find_country
    @country = Country.find_by_code(params[:id])
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_filter :get_data
  
  def index
    @currencies = Service.process :get_currencies
    @countries  = Country.all

    if params[:show_remained]
      @data = @data.reject{|d| # coz array is frozed
        !!@countries.find{|c| c.code == d[:country_code] && c.visited? }
      }
    end
  end

  def show
    countries = @data.find_all{|d| d[:currency_code] == params[:id] }.collect{|d| {:country => d[:country], :country_code => d[:country_code]}}

    respond_to do |f|
      f.js do
        render :json => {:countries => countries}
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

#  def new
#    @user = User.new
#  end
#
#  def create
#    @user = User.new(params[:user])
#    if @user.save
#      session[:user_id] = @user.id
#      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
#    else
#      render :action => 'new'
#    end
#  end

#  def edit
#    @user = current_user
#  end
#
#  def update
#    @user = current_user
#    if @user.update_attributes(params[:user])
#      redirect_to root_url, :notice => "Your profile has been updated."
#    else
#      render :action => 'edit'
#    end
#  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def offers_for_country(countries, hash)
    visited = countries.find_all{|c| c.code == hash[:country_code] && c.visited? }.size
    "Visited: #{visited}, Remain: #{hash[:offer_count] - visited}"
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/countries/_list.haml
%table
  %tr
    %td{:style => 'font-weight:bold'} Countries
  - for c in countries do
    %tr
      %td= link_to c.name, country_path(c.code)

app/views/countries/index.haml
%p
  = link_to 'Visited', visited_countries_path

= render 'list', :countries => @countries

app/views/countries/show.haml
%table
  %tr
    %td.bold Bought Currencies
    %td.bold At
    %td.bold Notes
  - for c in @country.country_currencies do
    %tr
      %td= c.visited_at
      %td= c.currency_code
      %td= c.notes

= form_for :country, :html => {:method => 'put'} do |f|
  Mark all currencies as bought
  = f.radio_button :buy_all, true
  UnMark All
  = f.radio_button :buy_all, false
  = f.submit 'update'

%p.bold
  Add Currency for this country
= form_for :country_currency, :url => buy_currency_country_path(@country.code) do |f|
  %p
    Visited At(yyyy-mm-dd)
    = f.text_field :visited_at, :size => 10
  %p
    Currency
    = f.select :currency_code, @data.collect{|d| d[:country_code] == @country.code ? d[:currency_code] : nil }.compact
  %p
    = f.text_area :notes, :rows => 2
  %p
    = f.submit 'update'

app/views/countries/visited.haml
%p
  = link_to 'All Countries', countries_path

= render 'list', :countries => @countries

app/views/currencies/index.haml
- if params[:show_remained]
  = link_to 'Show all', currencies_path
- else
  = link_to 'Show remained', currencies_path(:show_remained => true)

%table#currencies
  %tr
    %td{:style => 'font-weight:bold'} Currency
  - for hash in @data do
    - next if hash[:currency_code].blank?
    %tr
      %td= hash[:currency]
      %td.offers= offers_for_country(@countries, hash)
      %td{:id => "cur_#{hash[:currency_code]}"}

%style
  :sass
    .offers
      cursor: pointer
:javascript
  $(document).ready(function(){
    $('#currencies .offers').click(function(){
      var to = $(this).next();
      var code = to.attr('id').replace('cur_', '');

      $.ajax({
        url: '/currencies/' + code,
        type: 'get',
        dataType: "json",
        success: function(r){
          $.each(r.countries, function(index, c) {
            to.append($('<a>').text(c.country).attr('href', '/countries/' + c.country_code));
            to.append(' ');
          })
        }
      });
    })
  });

app/views/home/index.haml
%p= link_to 'Countries', countries_path
%p= link_to 'Currencies', currencies_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js' %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>

      <div style="float:right">
        <% if logged_in? %>
          Welcome <%= current_user.username %>! Not you?
          <%= link_to "Log out", logout_path %>
        <% else %>
          <%= link_to "log in", login_path %>
        <% end %>
      </div>

      <%= yield %>
      
    </div>
  </body>
</html>

app/views/users/_form.html.haml
= form_for @user do |f|
  = f.error_messages
  %p
    = f.label :username
    %br
    = f.text_field :username
  %p
    = f.label :email, "Email Address"
    %br
    = f.text_field :email
  %p
    = f.label :password
    %br
    = f.password_field :password
  %p
    = f.label :password_confirmation, "Confirm Password"
    %br
    = f.password_field :password_confirmation
  %p
    = f.submit (@user.new_record? ? "Sign up" : "Update")

app/views/users/edit.html.haml
- title "Sign up"

= render 'form'

app/views/users/new.html.haml
- title "Sign up"

%p== Already have an account? #{link_to "Log in", login_path}.

= render 'form'